#!/bin/bash
# Entrypoint / process supervisor for the hylafax+ container.
#
# Responsibilities, in order:
#   1. Render /var/spool/hylafaxplus/etc/config from FAX_* env vars.
#   2. Render etc/hosts.hfaxd (client ACL) from HYLAFAX_* env vars.
#   3. For each configured modem (MODEM_1_*, MODEM_2_*, ... up to MODEM_COUNT):
#      start iaxmodem (if type=iaxmodem), render etc/config.<devid>, start faxgetty.
#   4. Apply any operator-supplied override files from CUSTOM_CONFIG_DIR.
#   5. Start faxq and (optionally) hfaxd in the foreground, supervised.
#
# Every step is idempotent: re-running it (container restart) regenerates all
# generated files from the current environment. Anything under
# CUSTOM_CONFIG_DIR always wins - it is applied last.
set -Eeuo pipefail

SPOOL=/var/spool/hylafaxplus
CUSTOM_CONFIG_DIR="${CUSTOM_CONFIG_DIR:-/config-overrides}"
PIDS=()

log() { printf '%s [entrypoint] %s\n' "$(date -u +%FT%TZ)" "$*" >&2; }
die() { log "FATAL: $*"; exit 1; }

# ---------------------------------------------------------------------------
# 1. Global scheduler config (etc/config)
# ---------------------------------------------------------------------------
render_global_config() {
    log "rendering ${SPOOL}/etc/config"
    cat > "${SPOOL}/etc/config" <<EOF
CountryCode:            ${FAX_COUNTRY_CODE:-1}
AreaCode:               ${FAX_AREA_CODE:-000}
LongDistancePrefix:     ${FAX_LONG_DISTANCE_PREFIX:-1}
InternationalPrefix:    ${FAX_INTERNATIONAL_PREFIX:-011}
DialStringRules:        etc/${FAX_DIAL_RULES:-dialrules}
ServerTracing:          ${FAX_SERVER_TRACING:-1}
SessionTracing:         ${FAX_SESSION_TRACING:-0xFFF}
LogFacility:            ${FAX_LOG_FACILITY:-daemon}
TimeOfDay:              "${FAX_TIMEOFDAY:-Any}"
MaxDials:               ${FAX_MAX_DIALS:-12}
MaxTries:               ${FAX_MAX_TRIES:-3}
MaxConcurrentCalls:     ${FAX_MAX_CONCURRENT_CALLS:-1}
PostScriptTimeout:      ${FAX_POSTSCRIPT_TIMEOUT:-180}
EOF
    chown uucp:uucp "${SPOOL}/etc/config"
    chmod 0600 "${SPOOL}/etc/config"
}

# ---------------------------------------------------------------------------
# 2. Client access control (etc/hosts.hfaxd)
# ---------------------------------------------------------------------------
render_hosts_hfaxd() {
    log "rendering ${SPOOL}/etc/hosts.hfaxd"
    {
        echo "# Generated by entrypoint.sh - do not edit by hand, see CUSTOM_CONFIG_DIR"
        echo "127.0.0.1"
        echo "::1"

        if [[ -n "${HYLAFAX_ADMIN_USER:-}" && -n "${HYLAFAX_ADMIN_PASSWORD:-}" ]]; then
            local passwd_hash adminword_hash salt
            salt="$(openssl rand -hex 4)"
            passwd_hash="$(openssl passwd -6 -salt "${salt}" "${HYLAFAX_ADMIN_PASSWORD}")"
            adminword_hash="${passwd_hash}"
            if [[ -n "${HYLAFAX_ADMIN_ADMINWORD:-}" ]]; then
                adminword_hash="$(openssl passwd -6 -salt "$(openssl rand -hex 4)" "${HYLAFAX_ADMIN_ADMINWORD}")"
            fi
            echo "^${HYLAFAX_ADMIN_USER}@.*:0:${passwd_hash}:${adminword_hash}"
            log "admin user '${HYLAFAX_ADMIN_USER}' provisioned with administrative access"
        else
            log "HYLAFAX_ADMIN_USER/HYLAFAX_ADMIN_PASSWORD not set - no admin user provisioned, only localhost is trusted"
        fi

        if [[ -n "${HYLAFAX_ALLOW_HOSTS:-}" ]]; then
            IFS=',' read -ra hosts <<< "${HYLAFAX_ALLOW_HOSTS}"
            for h in "${hosts[@]}"; do
                echo "${h}"
            done
        fi
    } > "${SPOOL}/etc/hosts.hfaxd"
    chown uucp:uucp "${SPOOL}/etc/hosts.hfaxd"
    chmod 0600 "${SPOOL}/etc/hosts.hfaxd"
}

# ---------------------------------------------------------------------------
# 3. Per-modem setup
# ---------------------------------------------------------------------------

# Merge a config/<profile> prototype with a generated server-parameter block,
# the same substitution faxaddmodem(8C) performs between its
# "# BEGIN-SERVER" / "# END-SERVER" markers - see docs/CONFIGURATION.md.
render_modem_config() {
    local devid="$1" profile="$2" block_file="$3" out="${SPOOL}/etc/config.${devid}"
    local proto="${SPOOL}/config/${profile}"
    [[ -f "${proto}" ]] || die "unknown modem profile '${profile}' (no ${proto})"

    log "rendering ${out} from profile '${profile}'"
    awk -v blockfile="${block_file}" '
        /# BEGIN-SERVER/ { print; while ((getline line < blockfile) > 0) print line; skip=1; next }
        /# END-SERVER/   { skip=0 }
        skip            { next }
        { print }
    ' "${proto}" > "${out}"
    chown uucp:uucp "${out}"
    chmod 0600 "${out}"
}

start_iaxmodem() {
    local n="$1" devid="$2"
    local cfg="/etc/iaxmodem/${devid}"
    mkdir -p /etc/iaxmodem
    local -n _server="MODEM_${n}_IAX_SERVER"
    [[ -n "${_server:-}" ]] || die "MODEM_${n}_IAX_SERVER is required when MODEM_${n}_TYPE=iaxmodem"

    local -n _port="MODEM_${n}_IAX_PORT"
    local -n _peer="MODEM_${n}_IAX_PEER_NAME"
    local -n _secret="MODEM_${n}_IAX_PEER_SECRET"
    local -n _cidname="MODEM_${n}_IAX_CIDNAME"
    local -n _cidnumber="MODEM_${n}_IAX_CIDNUMBER"
    local -n _codec="MODEM_${n}_IAX_CODEC"
    local -n _refresh="MODEM_${n}_IAX_REFRESH"

    cat > "${cfg}" <<EOF
device          /dev/${devid}
owner           uucp
group           uucp
mode            660
refresh         ${_refresh:-900}
port            ${_port:-4569}
server          ${_server}
peername        ${_peer:-${devid}}
secret          ${_secret:-}
cidname         ${_cidname:-HylaFAX}
cidnumber       ${_cidnumber:-0000000000}
codec           ${_codec:-alaw}
EOF
    log "starting iaxmodem for ${devid} -> IAX2 server ${_server}:${_port:-4569} as peer '${_peer:-${devid}}'"
    /usr/sbin/iaxmodem "${devid}" >> "${SPOOL}/log/iaxmodem.${devid}.log" 2>&1 &
    PIDS+=("$!")

    for _ in $(seq 1 50); do
        [[ -e "/dev/${devid}" ]] && break
        sleep 0.2
    done
    [[ -e "/dev/${devid}" ]] || die "iaxmodem did not create /dev/${devid} in time"
    chown uucp:uucp "/dev/${devid}" || true
}

setup_modem() {
    local n="$1"
    local -n _type="MODEM_${n}_TYPE"
    local -n _device="MODEM_${n}_DEVICE"
    local -n _profile="MODEM_${n}_PROFILE"
    local -n _faxnumber="MODEM_${n}_FAX_NUMBER"
    local -n _localid="MODEM_${n}_LOCAL_ID"
    local -n _rings="MODEM_${n}_RINGS_BEFORE_ANSWER"
    local -n _tagline="MODEM_${n}_TAGLINE"
    local -n _cc="MODEM_${n}_COUNTRY_CODE"
    local -n _ac="MODEM_${n}_AREA_CODE"
    local -n _ld="MODEM_${n}_LONG_DISTANCE_PREFIX"
    local -n _idp="MODEM_${n}_INTERNATIONAL_PREFIX"

    local type="${_type:-iaxmodem}"
    local devid="${_device:?MODEM_${n}_DEVICE is required}"
    local profile="${_profile:-}"

    [[ -n "${profile}" ]] || { [[ "${type}" == "iaxmodem" ]] && profile="iaxmodem" || profile="class1"; }

    log "configuring modem ${n}: type=${type} device=${devid} profile=${profile}"

    case "${type}" in
        iaxmodem) start_iaxmodem "${n}" "${devid}" ;;
        serial)   [[ -e "/dev/${devid}" ]] || die "serial modem device /dev/${devid} not found - check the compose 'devices:' mapping" ;;
        *) die "unknown MODEM_${n}_TYPE '${type}' (expected 'iaxmodem' or 'serial')" ;;
    esac

    local block; block="$(mktemp)"
    {
        echo "CountryCode:            ${_cc:-${FAX_COUNTRY_CODE:-1}}"
        echo "AreaCode:               ${_ac:-${FAX_AREA_CODE:-000}}"
        echo "LongDistancePrefix:     ${_ld:-${FAX_LONG_DISTANCE_PREFIX:-1}}"
        echo "InternationalPrefix:    ${_idp:-${FAX_INTERNATIONAL_PREFIX:-011}}"
        echo "DialStringRules:        etc/${FAX_DIAL_RULES:-dialrules}"
        [[ -n "${_faxnumber:-}" ]] && echo "FAXNumber:              ${_faxnumber}"
        echo "LocalIdentifier:        \"${_localid:-HylaFAX}\""
        echo "ServerTracing:          ${FAX_SERVER_TRACING:-1}"
        echo "SessionTracing:         ${FAX_SESSION_TRACING:-0xFFF}"
        echo "RecvFileMode:           0600"
        echo "LogFileMode:            0600"
        echo "DeviceMode:             0660"
        echo "RingsBeforeAnswer:      ${_rings:-1}"
        [[ -n "${_tagline:-}" ]] && echo "TagLineFormat:          \"${_tagline}\""
        echo "MaxConcurrentCalls:     ${FAX_MAX_CONCURRENT_CALLS:-1}"
        echo "TimeOfDay:              \"${FAX_TIMEOFDAY:-Any}\""
    } > "${block}"

    render_modem_config "${devid}" "${profile}" "${block}"
    rm -f "${block}"

    log "starting faxgetty for /dev/${devid}"
    /usr/sbin/faxgetty -q "${SPOOL}" "/dev/${devid}" &
    PIDS+=("$!")
}

setup_all_modems() {
    local count="${MODEM_COUNT:-1}"
    for n in $(seq 1 "${count}"); do
        local devvar="MODEM_${n}_DEVICE"
        if [[ -z "${!devvar:-}" ]]; then
            log "MODEM_${n}_DEVICE not set - skipping modem slot ${n}"
            continue
        fi
        setup_modem "${n}"
    done
}

# ---------------------------------------------------------------------------
# 4. Operator escape hatch: CUSTOM_CONFIG_DIR overrides anything generated
#    above. Full flexibility for cases the env-var surface doesn't cover.
# ---------------------------------------------------------------------------
apply_custom_overrides() {
    [[ -d "${CUSTOM_CONFIG_DIR}" ]] || return 0
    shopt -s nullglob
    for f in "${CUSTOM_CONFIG_DIR}"/*; do
        local base; base="$(basename "${f}")"
        log "applying override: ${f} -> ${SPOOL}/etc/${base}"
        install -o uucp -g uucp -m 0600 "${f}" "${SPOOL}/etc/${base}"
    done
    shopt -u nullglob
}

# ---------------------------------------------------------------------------
# 5. Core daemons + supervision
# ---------------------------------------------------------------------------
shutdown() {
    log "shutting down (received signal)"
    for pid in "${PIDS[@]}"; do
        kill "${pid}" 2>/dev/null || true
    done
    wait || true
    exit 0
}

main() {
    mkdir -p "${SPOOL}/log" "${CUSTOM_CONFIG_DIR}" 2>/dev/null || true

    /sbin/syslogd -O /dev/stdout -n &
    PIDS+=("$!")
    sleep 0.3

    render_global_config
    render_hosts_hfaxd
    setup_all_modems
    apply_custom_overrides

    trap shutdown SIGTERM SIGINT

    log "starting faxq"
    /usr/sbin/faxq -D -q "${SPOOL}" &
    PIDS+=("$!")

    if [[ "${HFAXD_ENABLE:-yes}" == "yes" ]]; then
        log "starting hfaxd on ${HFAXD_BIND_ADDRESS:-0.0.0.0}:${HFAXD_PORT:-4559}"
        /usr/sbin/hfaxd -d -q "${SPOOL}" -l "${HFAXD_BIND_ADDRESS:-0.0.0.0}" -i "${HFAXD_PORT:-4559}" &
        PIDS+=("$!")
    fi

    log "ready - supervising ${#PIDS[@]} process(es): ${PIDS[*]}"
    # Exit (and let Docker's restart policy recover) as soon as any supervised
    # process dies, rather than silently running in a degraded state.
    wait -n "${PIDS[@]}"
    log "a supervised process exited - shutting down the rest"
    shutdown
}

main "$@"
